version: '3'
services:
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql_passwd
    volumes:
      - ./postgres/var/lib:/var/lib/postgresql/data
    networks:
            - postgres-network

  pgadmin4:
        image: dpage/pgadmin4:7.1
        container_name: pgadmin4
        restart: always
        environment:
            - PGADMIN_LISTEN_ADDRESS=pgadmin4
            - PGADMIN_LISTEN_PORT=5050
            - PGADMIN_DEFAULT_EMAIL=example@example.com
            - PGADMIN_DEFAULT_PASSWORD=pgadmin_passwd
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
            # - 'PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"'
        volumes:
            - ./pgadmin4/var/lib:/var/lib/pgadmin
        depends_on:
            - postgres
        ports:
          - 5050:5050
        networks:
            - postgres-network

networks:
    postgres-network:
        driver: bridge